# Generated by Django 4.1.7 on 2023-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uzytkownika', models.IntegerField()),
                ('nazwa', models.CharField(max_length=10)),
                ('opcjonalny_opis', models.TextField()),
                ('data_utworzenia', models.DateTimeField()),
                ('wlasciciel', models.IntegerField()),
                ('znacznik_dostepnosci', models.BooleanField()),
                ('data_zmiany_znacznika', models.DateTimeField()),
                ('data_ostatniej_zmiany_zawartosci', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=10)),
                ('opcjonalny_opis', models.TextField()),
                ('data_utworzenia', models.DateField()),
                ('własciciel', models.IntegerField()),
                ('znacznik_dostepnosci', models.BooleanField()),
                ('data_zmiany_znacznika', models.DateField()),
                ('data_ostatniej_zmiany_zawartosci', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja_pliku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ojca_sekcji', models.IntegerField()),
                ('id_ojca_plike', models.IntegerField()),
                ('opcjonalna_nazwa', models.CharField(max_length=10)),
                ('opcjonalny_opis', models.TextField()),
                ('data_utworzenia', models.DateField()),
                ('poczatek_sekcji', models.DateField()),
                ('koniec_sekcji', models.DateField()),
                ('rodzaj_sekcji', models.TextField()),
                ('status_sekcji', models.TextField()),
                ('dane_statusu', models.TextField()),
                ('tresc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=10)),
            ],
        ),
    ]
