# Generated by Django 4.1.7 on 2023-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plik',
            old_name='własciciel',
            new_name='wlasciciel',
        ),
        migrations.RenameField(
            model_name='sekcja_pliku',
            old_name='id_ojca_plike',
            new_name='id_ojca_pliku',
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='koniec_sekcji',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='poczatek_sekcji',
            field=models.IntegerField(),
        ),
    ]
