# Generated by Django 4.1.7 on 2023-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_rename_własciciel_plik_wlasciciel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekcja_pliku',
            name='znacznik_dostepnosci',
            field=models.BooleanField(default=True),
        ),
    ]
