# Generated by Django 4.1.7 on 2023-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_sekcja_pliku_znacznik_dostepnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='rodzic',
            field=models.IntegerField(default=0),
        ),
    ]
