# Generated by Django 4.1.7 on 2023-05-02 19:55

import datetime
from django.db import migrations, models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_katalog_rodzic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='id_uzytkownika',
        ),
        migrations.RemoveField(
            model_name='katalog',
            name='wlasciciel',
        ),
        migrations.RemoveField(
            model_name='sekcja_pliku',
            name='id_ojca_pliku',
        ),
        migrations.RemoveField(
            model_name='sekcja_pliku',
            name='id_ojca_sekcji',
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_ostatniej_zmiany_zawartosci',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 19, 55, 21, 661424)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 19, 55, 21, 661385)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_zmiany_znacznika',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 19, 55, 21, 661415)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='nazwa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='opcjonalny_opis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='znacznik_dostepnosci',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='dane_statusu',
            field=models.TextField(verbose_name=program.models.Dane_statusu),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='data_utworzenia',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 19, 55, 21, 681348)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='koniec_sekcji',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='opcjonalna_nazwa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='opcjonalny_opis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='poczatek_sekcji',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='rodzaj_sekcji',
            field=models.TextField(verbose_name=program.models.Rodzaj_sekcji),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='status_sekcji',
            field=models.TextField(verbose_name=program.models.Status_sekcji),
        ),
    ]
