# Generated by Django 4.1.7 on 2023-05-03 11:44

import datetime
from django.db import migrations, models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_dane_statusu_rodzaj_sekcji_status_sekcji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='data_ostatniej_zmiany_zawartosci',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 44, 22, 504373)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 44, 22, 504346)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_zmiany_znacznika',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 44, 22, 504365)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='dane_statusu',
            field=models.TextField(default=None, verbose_name=program.models.Dane_statusu),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='data_utworzenia',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 11, 44, 22, 521328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='status_sekcji',
            field=models.TextField(default=None, verbose_name=program.models.Status_sekcji),
        ),
    ]
