# Generated by Django 4.1.7 on 2023-05-03 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_alter_katalog_data_ostatniej_zmiany_zawartosci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='data_ostatniej_zmiany_zawartosci',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 51, 46, 841179)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 51, 46, 841153)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_zmiany_znacznika',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 51, 46, 841171)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='dane_statusu',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='data_utworzenia',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 11, 51, 46, 858601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='rodzaj_sekcji',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='status_sekcji',
            field=models.IntegerField(default=None),
        ),
    ]
