# Generated by Django 4.1.7 on 2023-05-03 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_alter_katalog_data_ostatniej_zmiany_zawartosci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='data_ostatniej_zmiany_zawartosci',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 1, 50, 788864)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 1, 50, 788838)),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='data_zmiany_znacznika',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 14, 1, 50, 788855)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='dane_statusu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='data_utworzenia',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 12, 1, 50, 805796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sekcja_pliku',
            name='status_sekcji',
            field=models.IntegerField(default=0),
        ),
    ]
